#!/usr/bin/env perl
use warnings;
use strict;

=pod

=head1 shhfiles (Show Or Hide Hidden Files) By Winston M. Cheng 2015

The script is designed to conviniently show or hide hidden files and
folders on OS X, by executing the commands on Terminal which normally
requires users to manually type them out. Users just type s or h.

=cut

sub showfiles
{
	print `defaults write com.apple.finder AppleShowAllFiles YES`;
	print `killall Finder`;
}

sub hidefiles
{
	print `defaults write com.apple.finder AppleShowAllFiles NO`;
	print `killall Finder`;
}

my $ans = "";
while($ans !~ /(exit|cancel|x|c)/i)
{
	print "Hide or Show hidden files (s/h): ";
	$ans = <>;
	last if $ans =~ /(exit|cancel|x|c)/i;
	if($ans =~ /\S/)
	{
		if($ans =~ /(hide|h)/i)
		{
			&hidefiles;
			last;
		}
		elsif($ans =~ /(show|s)/i)
		{
			&showfiles;
			last;
		}
		else
		{
			print "Not a valid option.\n";
		}
	}
	else
	{
		print "Not a valid option.\n"
	}
}
